feat: finish tutorial (#18)
* chore: add some storybook

https://redwoodjs.com/docs/tutorial/chapter5/first-story

* fix: enable show code button

https://github.com/storybookjs/storybook/issues/8104#issuecomment-932279083

* fix: better layout

* chore: make boilerplate stories

TODO have framework generate these

* fix: account for missing id on netlify

> Error: Variable "$id" of required type "Int!" was not provided.

* chore: fixup some tests

https://redwoodjs.com/docs/tutorial/chapter5/first-test

* chore: add `Comment`

yarn rw g component Comment
https://redwoodjs.com/docs/tutorial/chapter6/the-redwood-way

* chore: add some boilerplate

* chore(Comment): improve and wire up some mock data

https://redwoodjs.com/docs/tutorial/chapter6/the-redwood-way#storybook

* chore: add styling

* chore: add CommentsCell

https://redwoodjs.com/docs/tutorial/chapter6/multiple-comments

* chore: add some boilerplate

* chore: add better mocks

* chore: update CommentsCell

* chore: add a bit more styling

* chore: add comments

TODO figure out loading part of this

* chore: fix

* chore: add Comments to the schema

https://redwoodjs.com/docs/tutorial/chapter6/comments-schema

* chore(prisma): generate Comment table migration

* chore(prisma): generate Comment table migration

* chore(ide): add recommended extension

* chore: remove unused routes in main app

* Revert "chore: remove unused routes in main app"

This reverts commit 53637f81d8be369c515b02d4c7cf02b41b396492.

* chore: disable contact/login forms

not used

* chore: remove unused import

* test(unit): add example async test

* test(unit): default summary to true

* chore: update empty comments cell

https://redwoodjs.com/docs/tutorial/chapter6/comments-schema

* chore(comments): allow/create

https://redwoodjs.com/docs/tutorial/chapter6/comments-schema

* chore(commentForm): run generator

`yarn rw g component CommentForm`
https://redwoodjs.com/docs/tutorial/chapter6/comment-form

* chore(commentForm): add some boilerplate

* chore(commentForm): simple form

* chore(commentForm): add submit

* chore(storybook): wire up mockGraphQLMutation

* chore(storybook): add interaction test

https://stackoverflow.com/a/63745654

* chore: fixup style

* test(unit): better test

* test: add loading snapshot

* chore(commentForm): use form

https://redwoodjs.com/docs/tutorial/chapter6/comment-form#adding-the-form-to-the-blog-post

* chore(commentForm): wire up correctly in Article

* chore(contactForm): refetch comments after create

https://redwoodjs.com/docs/tutorial/chapter6/comment-form#graphql-query-caching

* chore: add toast feedback for form

https://redwoodjs.com/docs/tutorial/chapter6/comment-form#graphql-query-caching

* chore: wire up comments to posts correctly

* chore: fixup prod/dev routes

* chore: get comment by post

* chore(rbac): add roles to user

https://redwoodjs.com/docs/tutorial/chapter7/rbac

* chore(rbac): gate admin page

* chore(rbac): add seed script

* chore: add default route for /admin

* chore(rbac): add delete button

also wire up test/story
https://redwoodjs.com/docs/tutorial/chapter7/rbac#mocking-currentuser-for-jest

* chore: gate delete call

* chore: allow admin to delete as well

* chore(rbac): wire up delete gating

* test(unit): simplify

* fix(storybook): add explicit imports for Netlify

* build(🧶): add reslutions for `@storybook/*`

transitive dependencies of redwood