Revert "fix(storybook): add temporary patch for `TypeError: e.replace is not a function` (#71)" (#79)
This reverts commit 025fc512f38ef5f7838eba3e5c0833702ade0d5e.

# Conflicts:
#	package.json
#	yarn.lock

closes #72
see also: https://github.com/redwoodjs/example-storybook/issues/72#issuecomment-1136029296